# Generated by Django 5.1.12 on 2025-09-08 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketlog",
            name="action_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action (null for system actions)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
