# Generated by Django 5.1.12 on 2025-09-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number for contact",
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="TwoFactorCode",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
