# Generated by Django 5.1.12 on 2025-09-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userprofile_twofactorcode"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Email address for authentication",
                max_length=254,
                unique=True,
            ),
        ),
    ]
