# Generated by Django 5.1.12 on 2025-09-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Optional username field",
                max_length=150,
                null=True,
            ),
        ),
    ]
