# Generated by Django 5.1.12 on 2025-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether two-factor authentication is enabled for this user",
            ),
        ),
    ]
